trigger:
  branches:
    exclude:
      - '*'

pr:
  branches:
    include:
      - '*'

pool:
  vmImage: 'windows-latest'

steps:
  - script: echo Hello, world!
  - script: echo This is a build step.

# Ajoutez les étapes pour votre processus de release ici
