# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Default
variables:
  APP_SERVICE_NAME: 'soatflaskapp'
  RESOURCE_GROUP_NAME: 'training-rldahou-rg'
  MyPrivateKey: |
    -----BEGIN PRIVATE KEY-----
    LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQ0KTUlJRzRnSUJBQUtDQVlF
    QXNkbG5nbWRla25zSFJ2YzhYbU5sWlZOZ2M4R2JGWW8yblVpNWY3OGN6YmpPM3Bw
    NA0KMGIyUEZCOVBkK1RtRUtwT0NzbUF3ZW5MMXhMQWJFUUlBUGkrTkNUdzRBdGlx
    T0t5UVlNSDNOQXNDNUE5ampoYg0KMDU3TmYxQ3R0NHhzSGtrQUYzUlBVaklVOVN2
    NzJ5YlhxQVlzRloxaUY0dU9raktrSFUyNHkvZUxNN01hbTUyQw0KS2xIbk5Wdlor
    SjRKOS9BTE53aUJtVEtZWnQxdnhkOExZM2hZc3Z1SnpYc1I2MUNFWVRQWUtycE02
    TEVMT1lNQQ0KcWRSQ2dVcUhCU1ZVVisxKzluMGl1REdhQ3hUT3QvWnlLeEdsUlBI
    SytSVWgxb211RmdrSWdNSlJCM2swV3cyUA0KYm1Cem45RnB2eVNWMVNzaWJ0RGpJ
    YkUxK1BHNFB3aFN4TE94bkdBdGEwcmo3Ukx2L0lpWmVNNXNkLzQ0Sm1VZg0KdUly
    eEJqRUVUYTN6Yjk2amptYVpXWlJnNzdzMUJvS212UG52blZFZ2lLNUFBZ0Jobjh2
    cU90N3JGajVOWFA4Yg0KOWYwbDRnWnJHZENRM3Faa0tVV3RJdnR1WFNPZVp1Z1Ey
    QWUwSzNSdmR6OTFHeitNSHJDK0U2dnc0eWFqUmdFMQ0KTGNiRzQyRzkzUkFMMGV5
    cEFnTUJBQUVDZ2dHQVB1S1ZkQW1pNmY1d2UwcE9ZVDJhQzdMb2h1V3ROWGVTaWhp
    OQ0KNW9xbjM2SDZHOEhZK0tpakg4VldieGxUdEE3VDI0S1djWHArcGdTdVgxbkt6
    clVsWkFDdjN6aUhZUm9QVjVUQw0KUWZTbHJrMEpSdkZzbnE0bkVWNXdubGNibjdY
    R1A0VFR5MGVFRzVDNjFDbXUxVzJoUnQ5SVlQVHFxNDBXZEhvWA0KM3A4ZjdGN25D
    S0V2OWxEUmhROStTaWR2ZE9pK3ZtM1dqVm5UZzRQRzB0dGtCbjcyTmdzMUZaL3Zu
    Um55UlFCMA0KN2Q3RDlQOHM3ZUFCYXd0dm5KSENuakl0MlkxUzRRempBYkp0VWhl
    ZEl2clc0OHR0eTNNSElJUXNYN2hlL0Exbg0KUGtRMDFnamVuZnpMVXI0VG9HVDAv
    eEtNSFhrTmVJSzdkVFZKcDdzUXdLVVdybUNHdlg1bDNiWGVtZHdBd2tXNA0KUFo3
    b0RFa0k5ckh4NnZ5YzRKcW52RW5UdFlUVmFxWEdVK0JlUysrRTlzZjRNa2l3Sm51
    VU1DTkhuM3FJTnFrYw0KY0tMd3dPVlN6ai9rUTV2ZlMvbXNtNGlxd3Q3bzlROFhF
    NGlXV1Z0S0xuelkrRkxpNVk2NjVyVy9qVHAxZUdTeg0KSUdxZkxKYXVYQ0NhS3A0
    WWk3ZWxsOUp6N3huVkFvSEJBTWRpMEpVUmlUZlgzREtjT0JqTzZUaUl3d2NlY05m
    ag0KR3ZOcnZ6WThFYW9GbnlWcm5neThTaCtQNld6Tmo1Z0M4NjdIQkZGemc0NC81
    bmVJN2t3dHJ4bVVON2pNRWU3eQ0KMFEvemdLVWpaamYzTUdaQjJ0Q3p0VUdFa3Fv
    TS9TUDRDNTVDbGQ0Q1QyNmVxUEp0TU9OcFhOb1FBQ2NidWFqQg0KT2laNXhtcmFB
    U255RGcvV1FsNnQ1MFJNQzVrT0xXajhUekEwNE5QQ1A2aGtOTHNWVDc2QjBlbjBS
    UWgxOHNoYQ0KRGhmTWJ2YkYwQlZUZWo3S2dkbHZ6cDhOdHZzb2lZaW5Fd0tCd1FE
    a1dSb3REVkYxRitjdzJnTktwMkZmamZTMw0KZjIvQzZOUXpDWm9wU2Y2RHRqRHNY
    NFhhQ3JNT3FTSE0zdnRlT3hpbU5TZDQ4cDdvTHpaai92bCtoK3R4b0t3Yw0KRnJx
    VFI2eXJaZGVDM2I4VXZqbStJNk5UOTF4U2h0QWJDSUpETUlBOGR2STkzUTVKUk8w
    akZqdmh0VGs3c2d1RQ0KRHBiTS83N3hIVmZ5b0ZXZ0Y2cE1zdXpML2loOWI5MEZR
    aElHRkM2MnE2dFRoa1dtNk0wY1dlUXZKT3M3Z1kxNg0KZFA1NVhQajhSZ0dHc09n
    VnF0TzJNV0lzVzBQeGVKY1VBN245Nk5NQ2djQjJ0WXR3SlVlb090bThQQ3hlQU5y
    MA0KTU9ERTNVZmNFVGZiazl2OVExaFUvUkhhcXE4bjcvYkZ3ZDM5VEluZ3ZHa3ZO
    d2lJSWhsQ1dTTXpLaENPeEdoSw0KOTJjUm5GWlZDTGFXSTZrRktRVlQ3dFVmSExo
    VnA1a1VFQVZ1UDF0N3pkUEUvdW5SaTFpVmlOc1hzeEQzWktURw0Kbzk0amFxdG9J
    TnNwU3pscUpxK290SmZRc0FWRjc0NFFxS0lERjJETDcrU0oxQUhEc2hSS2dwYXVp
    Q3E1UnZ1ZQ0KcWpOcnJTWEdTVys0bFp1L1N0anZ5WXF2MWN2bmxGelZiOG53MFJy
    SmhJY0NnY0J6eThOOGFTNlBwSWwydW5mRQ0KMmRDRk5tV00wREVLdENzM25uend4
    emNyNzY0cmo5MCt6d0l5UXc2QzUraXN4bWNma2dEc1Vvekd6WHBWaHkxYQ0KUHU3
    a2RrZ1JEbTJhMWxQM3J2TjB4Nkpva0hhVHQxclI3N1IvblNIWE01OXJGeU5RaGpr
    ZHFnWGVuZmRyUFpFcw0KU2t3MXUzb2ZnNDV4Y3BlUGlnUFpZL2xINy9oS1lNbTRR
    TENqdTZCblZEUHpwVFJ6S2ViOXVpK0VEclpFMUVqaw0KcDJJcWtPMy8xV2hlZndr
    OFZQdmRJOFR0aCsxSWpRNXQwL0pHZDVLVmNiWlZ6a1VDZ2NBOGFpdlFCc1Q1ZUVt
    bw0KS2xDS2tpR3hQTmFsc3Z3cmVGa2Y3WnhEa3BsSDByclVpUitOUmZYcGdsZHZs
    WGU5bUVsblloTDZYN3BaT3BWVg0KOGdmRHp0VDJzUzN6anVsSVJTR3NyaHg1M1Rh
    SncvQWV4ZVRtb2ZPU29GTitLSkIzZ085cUlYN2xvK1F3TzU1Lw0KTUdhcktxVmhW
    ZUpFanpRdU9GbVBmaWM1RTNWeW9sbzJWamtIdnlpSlZiak1rQ0hZbUZsQWt2eTJQ
    OVR5RkhLdA0KakNkQlJFekxmWVZ2Zzh6WE5KVFlPMElETnkwRVhWVDVwN0FPaUIv
    eWhPRTd1ak1oVEF3PQ0KLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0NCg==
    -----END PRIVATE KEY-----

steps:
- task: CopyFiles@2
  inputs:
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    OverWrite: true
- task: CmdLine@2
  displayName: 'Test code quality'
  inputs:
    script: |
      echo Test code quality
      python3 flake8.py
  continueOnError: false
- task: CmdLine@2
  displayName: 'Build Docker images'
  inputs:
    script: |
      echo Build Docker images
      sudo docker build -t flasapp .
    workingDirectory: '$(Build.ArtifactStagingDirectory)'
  continueOnError: false
- task: CmdLine@2
  displayName: 'Test container'
  inputs:
    script: |
      echo Test container
      sudo docker run --rm -p 8000:8000 flasapp bash -c "python3 app.py & sleep 2 && curl -X POST -d 'name=Renaud' http://localhost:5000/hello"
    workingDirectory: '$(Build.ArtifactStagingDirectory)'
  continueOnError: false
- task: CmdLine@2
  displayName: 'Achives file'
  inputs:
    script: 'zip -r app.zip ./*'
    workingDirectory: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  displayName: 'Publish artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/app.zip'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  continueOnError: false

- task: CmdLine@2
  displayName: 'Run as Appservice'
  inputs:
    script: 'az webapp deploy --name $APP_SERVICE_NAME --resource-group $RESOURCE_GROUP_NAME --src-path $(Build.ArtifactStagingDirectory)/app.zip'